language: node_js
node_js:
- node
sudo: false
script:
- npm test
deploy:
  provider: heroku
  api_key:
    secure: CuRBDzLKuMEYAiVx85DcOAbz2NL7drmP/S6vVlPWMPBI4z5vsUjkg90fco+cUroVqY64JG/2e2KkdVqprGh74egO5IU3e6rRlJfZ32xjY7ZWY9b3d8c8wO7KvqQRBDcJA79wZolBB+r/y+MCMAqZNJlWyIAvn/V3oEp7dSHGZV0G6xkpEB8yb7U06jn0bc/A/pN5CyT7r8ndMD81NprVigKGvsxtxzXdtLu4djrdT/cR63WjEA+UAxZp93dfRVcvka8D7GyBOraNKGf1TrVoaW1rje4bU1uPhUIHnzIwGUG52I3kMYGh9mK3spW2NDfWJwajGKIw2WpXDM7F0/BpgDA2dPWPaZ0HiRg7aHszAnZC7zgFvRFaHC0oy0wvBE8OkJeQqEQBJQq+832WzjNLQSuVdEEkQy4QiWwoIsHwHGY8LUScG4dW7FAMzpD0Ucr4rCNPKAQnozUw/xYQRVu1yJ0MZdDxCq+l6jo15l7LxVAjRVP6aoZL/ujOa5f4roa6nUwV+7oyPLuf477BAmx0K8j9wz1URLHRSdDMskF+l/BfDsJUeA2A8coLC3j5oOeb3Tkhwe/dDr2IW3taMguNvrp0H2uAY98J3BE+qhZvMRqExsaRXETenN/Cu9mY+JC7r9KUVvEJxyqOWT4sCglQ0cW+id+vhO6Qe/Dirmcq0ng=
  app: devops-pratica-pipeline
  edge: true
