language: node_js
node_js:
- node
sudo: false
script:
- npm test
deploy:
  provider: heroku
  api_key:
    secure: F0ai31+5qXNspbP1ARTbwcyB/2nQ9kym+DSzdN31lZvpwP8pBcaus/rEksckBfw++oNcN3FyVk3ZvKevhS2de3wDhQj8KTTRPRUqtCfGmy3swJ0F/FDqZiPRDdf/dQgyfgYYBkhZ6FxfBIVylG/DjbrBS78i55LSC2ygFvdrxzxXOC3wBwnXvDPhtD8AVqQ3R+6zLyU15AioVgzaSoDc9r71Q4WQSbbPQvBjH+gGEb2ARrvofL7IY+tE2WVAPIMyH/2VMz52m7zcFs4H6howlGpA8qj25gLQdijjGaYiyV5o/QdWafuFnz/4BUZZzA4LPZPyIa5v9PuHRw4jVAlJCy9lwEEaPjW3OD4KuRgmb2fbQJb81BCV9yPeJLRh8LK0KFgUFOF/ZaCuCuqdj5R1PDtbLrll6Z1ALAdaaywsKt/swpysjtfaTzKM9LsmRUCeKZmXwKQHtZBfRLsovgPX1s+NKQC2qrTbyx2KCtw0AXIJax3MDFrth5sChOOLQHesYdW7nmYEyoWAX2z/aR08Eir9BDF+df2P0vlfBaMG7jZHWvh6Ze3pxqsRqQGHNkIl1N3WzozQAHKhRGhqXelQ3vODioji3aO98IgnQVzE12AIxkrosVkW3UywSuvN6NIB9Zd9igRqJvjtRgcfasChhyeRUL+U5zOLqKEnwCpdVv0=
  app: devops-pratica-pipeline
  edge: true
