language: node_js
node_js:
- node
sudo: false
script:
- npm test
deploy:
  provider: heroku
  api_key:
    secure: up3sPMOcitDpWTWV/rFLxho/wyfKEtpeHbPkpDxu1aVsNefNhWV8BoPQxQNNqYTCZwpNL9O2ZLNmtWhxj17no0SWXpc3tYBTRUQviqS8/NjIprp9sTzP1A/D7KCqRZHSQKNcIs8QY22IFHBbcEVfsZDr/3VF+s5wD4VDgS5iGrd29mHE2BqnEt2VahGPIQyrCxAjPnIvdbDUJ5/aLao83YObvIxeOml/ctY8exOE7lWBhSHIY1c6PdQLgatraVPgIk/vXcVKR8E1ykUulEwLzNovRreLf5nbiTOVZFCRAPUFu+l8YCovdfMW2yemOUuA/ZebqW7f878HYt7cL67kpPAqsJBTh1LGUt04tHjSEJcs4pMRdBzkYc2NqvfH9CiWrqPPVDJcFn14GcLagEpzgthAzALXYWmwTSSz8xkJkUfYB+HBdjriHbM3f77NWytEsXpbdt3m3y3asimvk9BxYPJr6Py131PxLfHIXnxmVCWnbRZxx5cIK6WtxPwKDoGKnV8O2y7N9MNfSBpk+cm3inRFoxsr/dyEL4NHv3L9eQ8OHRF6IylaYeaNswCdchy1EtYBALl9D2mX//b0buYNvV/FGTRP37oIl4HxzMSmC1EuN3d1ZGrpohoisQDrTLUEL+yR7EBwukd47L7lc9PEZt2mv1WSYx7956SvTXsAmbk=
  app: devops-pratica-pipeline
  edge: true
